#include <exception.h>
#include <testexception.cpp>
#include <iostream>
#include <exeption.cpp>

using namespace std;

int main()
{
    TestException();
    return 0;
}
